swiftmailer:
    spool: { type: 'memory' }
    transport: '%mailer_transport%'
    host:      '%mailer_host%'
    port:      '%mailer_port%'
    encryption: '%mailer_encryption%'
    username:  '%mailer_user%'
    password:  '%mailer_password%'
    authmode: '%mailer_authmode%'
    
    